spring.application.name=job
server.port=8082
welcome.message=welcome to job service
#eureka registation
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888